verify secrets

diff --git a/.github/workflows/cicd.yml b/.github/workflows/cicd.yml
--- a/.github/workflows/cicd.yml
+++ b/.github/workflows/cicd.yml
@@ -43,22 +43,33 @@ jobs:
             echo "✅ RENDER_SERVICE_ID is set!"
           fi
 
-      - name: Validate all required secrets
-        run: |
-          missing=""
+          if [[ -z "${{ secrets.CLOUD_NAME }}" ]]; then
+            echo "❌ CLOUD_NAME is missing!"
+            exit 1
+          else
+            echo "✅ CLOUD_NAME is set!"
+          fi
 
-           if [ -z "${{ secrets.CLOUD_NAME }}" ]; then echo "❌ CLOUD_NAME is missing"; missing="yes"; fi
-           if [ -z "${{ secrets.CLOUD_KEY }}" ]; then echo "❌ CLOUD_KEY is missing"; missing="yes"; fi
-           if [ -z "${{ secrets.CLOUD_SECRET }}" ]; then echo "❌ CLOUD_SECRET is missing"; missing="yes"; fi
-           if [ -z "${{ secrets.VDOCIPHER_API_SECRET }}" ]; then echo "❌ VDOCIPHER_API_SECRET is missing"; missing="yes"; fi
-           if [ -z "${{ secrets.ACCESS_TOKEN_SIGN_IN }}" ]; then echo "❌ ACCESS_TOKEN_SIGN_IN is missing"; missing="yes"; fi
+          if [[ -z "${{ secrets.CLOUD_KEY }}" ]]; then
+            echo "❌ CLOUD_KEY is missing!"
+            exit 1
+          else
+            echo "✅ CLOUD_KEY is set!"
+          fi
 
-           if [ "$missing" = "yes" ]; then
-             echo "🚨 Exiting due to missing secrets."
-             exit 1
-           else
-             echo "✅ All required secrets are set."
-           fi
+      # - name: Validate all required secrets
+      #   run: |
+      #     missing=""
+
+      #      if [ -z "${{ secrets.CLOUD_NAME }}" ]; then echo "❌ CLOUD_NAME is missing"; missing="yes"; fi
+      #      if [ -z "${{ secrets.CLOUD_KEY }}" ]; then echo "❌ CLOUD_KEY is missing"; missing="yes"; fi
+
+      #      if [ "$missing" = "yes" ]; then
+      #        echo "🚨 Exiting due to missing secrets."
+      #        exit 1
+      #      else
+      #        echo "✅ All required secrets are set."
+      #      fi
 
       - name: Build Docker image
         run: docker build -t e-learning-server .
